'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'bn' | 'banglish';

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Dena-Paona',
    tagline: 'Finance Ledger',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    addTransaction: 'Add Transaction',
    contacts: 'Contacts / Search',
    activityLog: 'Activity Log',
    profile: 'Profile',
    adminPanel: 'Admin Panel',
    manageUsers: 'Manage Users',
    logout: 'Logout',
    mainMenu: 'Main Menu',
    administration: 'Administration',
    welcomeBack: 'Welcome back',
    signIn: 'Sign In',
    signInSubtitle: 'Sign in to your Dena-Paona account',
    emailOrUsername: 'Email or Username',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    createAccount: 'Create account',
    totalPaona: 'Total Paona (Receivable)',
    totalDena: 'Total Dena (Payable)',
    netBalance: 'Net Balance',
    contactLedger: 'Contact Ledger',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    recordPaona: '📥 Record Paona (Someone owes you)',
    recordDena: '📤 Record Dena (You owe someone)',
    searchUsers: '🔍 Search Users',
    noTransactions: 'No transactions yet',
    addFirst: 'Add your first transaction to start tracking',
    paona: 'Paona',
    dena: 'Dena',
    amount: 'Amount',
    paid: 'Paid',
    remaining: 'Remaining',
    status: 'Status',
    date: 'Date',
    actions: 'Actions',
    pending: 'Pending',
    partial: 'Partial',
    cleared: 'Cleared',
    contact: 'Contact',
    type: 'Type',
    notes: 'Notes',
    search: 'Search',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    viewAll: 'View All →',
    loading: 'Loading...',
    moneyOweYou: 'Money others owe you',
    moneyYouOwe: 'Money you owe others',
    fullName: 'Full Name',
    username: 'Username',
    email: 'Email',
    phone: 'Phone',
    age: 'Age',
    gender: 'Gender',
    accountInfo: 'Account Information',
    security: 'Security',
    memberSince: 'Member Since',
    totalUsers: 'Total Users',
    verifiedUsers: 'Verified Users',
    bannedUsers: 'Banned Users',
    totalTransactions: 'Transactions',
    totalVolume: 'Total Volume',
    ban: 'Ban',
    unban: 'Unban',
    makeAdmin: '↑ Admin',
    removeAdmin: '↓ Remove',
    joined: 'Joined',
    recordPayment: 'Record Payment',
    paymentAmount: 'Payment Amount',
    paymentHistory: 'Payment History',
    outstandingBalance: 'Outstanding Balance',
    fullyCleared: 'Fully Cleared!',
    addNew: '➕ Add New',
    back: '← Back',
    searchPlaceholder: 'Search contacts...',
    noActivity: 'No activity yet',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    settings: 'Settings',
    verifyEmail: 'Verify Your Email',
    verificationCode: 'Verification Code',
    verifyBtn: '✅ Verify Email',
    resendCode: '📨 Resend Code',
    backToLogin: '← Back to Login',
    createYourAccount: 'Create Your Account',
    joinSubtitle: 'Join Dena-Paona and start tracking your finances',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    selectGender: 'Select gender',
    passwordStrengthWeak: 'Weak',
    passwordStrengthMedium: 'Medium',
    passwordStrengthStrong: 'Strong',
    passwordStrength: 'Password strength',
    confirmPassword: 'Confirm Password',
    alreadyHaveAccount: 'Already have an account?',
    setUsername: 'Set Your Username',
    usernameHint: 'Choose a unique username (3-30 chars, letters/numbers/_)',
    usernameAvailable: 'Username is available!',
    usernameTaken: 'Username already taken',
    completeProfile: 'Complete Your Profile',
    completeProfileSubtitle: 'Add more details so others can find you easily',
    skipForNow: 'Skip for now',
    bkashAvailable: 'I accept bKash / mobile banking payments',
    profilePicture: 'Profile Picture',
    uploadPhoto: 'Upload Photo',
    changePhoto: 'Change Photo',
    forgotPasswordTitle: 'Forgot Password?',
    forgotPasswordSubtitle: 'Enter your email and we\'ll send a reset code',
    sendResetCode: 'Send Reset Code',
    resetPassword: 'Reset Your Password',
    resetCode: 'Reset Code',
    newPassword: 'New Password',
    pendingApproval: 'Pending Approval',
    approved: 'Approved',
    disputed: 'Disputed',
    forceApproved: 'Force Approved (Admin)',
    approvePayment: 'Approve Payment',
    disputePayment: 'Dispute Payment',
    disputeReason: 'Dispute Reason',
    disputeProof: 'Proof (URL or description)',
    profileCompleted: 'Profile Completed',
    profileIncomplete: 'Complete Your Profile',
    completeProfileBanner: 'Your profile is incomplete. Complete it to build trust with others.',
  },
  bn: {
    appName: 'দেনা-পাওনা',
    tagline: 'আর্থিক লেজার',
    dashboard: 'ড্যাশবোর্ড',
    transactions: 'লেনদেন',
    addTransaction: 'লেনদেন যোগ করুন',
    contacts: 'পরিচিতি / অনুসন্ধান',
    activityLog: 'কার্যকলাপ লগ',
    profile: 'প্রোফাইল',
    adminPanel: 'অ্যাডমিন প্যানেল',
    manageUsers: 'ব্যবহারকারী পরিচালনা',
    logout: 'লগ আউট',
    mainMenu: 'মূল মেনু',
    administration: 'প্রশাসন',
    welcomeBack: 'আবার স্বাগতম',
    signIn: 'সাইন ইন',
    signInSubtitle: 'আপনার দেনা-পাওনা অ্যাকাউন্টে সাইন ইন করুন',
    emailOrUsername: 'ইমেইল বা ইউজারনেম',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    totalPaona: 'মোট পাওনা (প্রাপ্য)',
    totalDena: 'মোট দেনা (পরিশোধযোগ্য)',
    netBalance: 'নেট ব্যালেন্স',
    contactLedger: 'পরিচিতি লেজার',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    quickActions: 'দ্রুত পদক্ষেপ',
    recordPaona: '📥 পাওনা রেকর্ড করুন (কেউ আপনার কাছে ঋণী)',
    recordDena: '📤 দেনা রেকর্ড করুন (আপনি কারো কাছে ঋণী)',
    searchUsers: '🔍 ব্যবহারকারী খুঁজুন',
    noTransactions: 'এখনো কোনো লেনদেন নেই',
    addFirst: 'ট্র্যাকিং শুরু করতে প্রথম লেনদেন যোগ করুন',
    paona: 'পাওনা',
    dena: 'দেনা',
    amount: 'পরিমাণ',
    paid: 'পরিশোধিত',
    remaining: 'বাকি',
    status: 'অবস্থা',
    date: 'তারিখ',
    actions: 'পদক্ষেপ',
    pending: 'মুলতুবি',
    partial: 'আংশিক',
    cleared: 'পরিষ্কার',
    contact: 'পরিচিতি',
    type: 'ধরন',
    notes: 'নোট',
    search: 'অনুসন্ধান',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    viewAll: 'সব দেখুন →',
    loading: 'লোড হচ্ছে...',
    moneyOweYou: 'অন্যরা আপনার কাছে যা ঋণী',
    moneyYouOwe: 'আপনি অন্যদের কাছে যা ঋণী',
    fullName: 'পূর্ণ নাম',
    username: 'ইউজারনেম',
    email: 'ইমেইল',
    phone: 'ফোন',
    age: 'বয়স',
    gender: 'লিঙ্গ',
    accountInfo: 'অ্যাকাউন্ট তথ্য',
    security: 'নিরাপত্তা',
    memberSince: 'সদস্যপদ থেকে',
    totalUsers: 'মোট ব্যবহারকারী',
    verifiedUsers: 'যাচাইকৃত ব্যবহারকারী',
    bannedUsers: 'নিষিদ্ধ ব্যবহারকারী',
    totalTransactions: 'লেনদেন',
    totalVolume: 'মোট পরিমাণ',
    ban: 'নিষিদ্ধ করুন',
    unban: 'নিষেধাজ্ঞা তুলুন',
    makeAdmin: '↑ অ্যাডমিন',
    removeAdmin: '↓ সরান',
    joined: 'যোগ দিয়েছেন',
    recordPayment: 'পেমেন্ট রেকর্ড করুন',
    paymentAmount: 'পেমেন্টের পরিমাণ',
    paymentHistory: 'পেমেন্ট ইতিহাস',
    outstandingBalance: 'বকেয়া ব্যালেন্স',
    fullyCleared: 'সম্পূর্ণ পরিষ্কার!',
    addNew: '➕ নতুন যোগ করুন',
    back: '← ফিরে যান',
    searchPlaceholder: 'পরিচিতি খুঁজুন...',
    noActivity: 'এখনো কোনো কার্যকলাপ নেই',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    language: 'ভাষা',
    settings: 'সেটিংস',
    verifyEmail: 'আপনার ইমেইল যাচাই করুন',
    verificationCode: 'যাচাইকরণ কোড',
    verifyBtn: '✅ ইমেইল যাচাই করুন',
    resendCode: '📨 কোড পুনরায় পাঠান',
    backToLogin: '← লগইনে ফিরুন',
    createYourAccount: 'আপনার অ্যাকাউন্ট তৈরি করুন',
    joinSubtitle: 'দেনা-পাওনায় যোগ দিন এবং আর্থিক ট্র্যাকিং শুরু করুন',
    male: 'পুরুষ',
    female: 'মহিলা',
    other: 'অন্যান্য',
    selectGender: 'লিঙ্গ নির্বাচন করুন',
    passwordStrengthWeak: 'দুর্বল',
    passwordStrengthMedium: 'মাঝারি',
    passwordStrengthStrong: 'শক্তিশালী',
    passwordStrength: 'পাসওয়ার্ডের শক্তি',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    setUsername: 'ইউজারনেম সেট করুন',
    usernameHint: 'একটি অনন্য ইউজারনেম বেছে নিন (৩-৩০ অক্ষর)',
    usernameAvailable: 'ইউজারনেমটি পাওয়া যাচ্ছে!',
    usernameTaken: 'ইউজারনেমটি ইতিমধ্যে নেওয়া হয়েছে',
    completeProfile: 'প্রোফাইল সম্পন্ন করুন',
    completeProfileSubtitle: 'আরও তথ্য যোগ করুন যাতে অন্যরা আপনাকে খুঁজে পেতে পারে',
    skipForNow: 'এখনের জন্য এড়িয়ে যান',
    bkashAvailable: 'আমি বিকাশ / মোবাইল ব্যাংকিং পেমেন্ট গ্রহণ করি',
    profilePicture: 'প্রোফাইল ছবি',
    uploadPhoto: 'ছবি আপলোড করুন',
    changePhoto: 'ছবি পরিবর্তন করুন',
    forgotPasswordTitle: 'পাসওয়ার্ড ভুলে গেছেন?',
    forgotPasswordSubtitle: 'আপনার ইমেইল দিন এবং আমরা একটি রিসেট কোড পাঠাব',
    sendResetCode: 'রিসেট কোড পাঠান',
    resetPassword: 'পাসওয়ার্ড রিসেট করুন',
    resetCode: 'রিসেট কোড',
    newPassword: 'নতুন পাসওয়ার্ড',
    pendingApproval: 'অনুমোদন বাকি',
    approved: 'অনুমোদিত',
    disputed: 'বিতর্কিত',
    forceApproved: 'অ্যাডমিন অনুমোদিত',
    approvePayment: 'পেমেন্ট অনুমোদন করুন',
    disputePayment: 'পেমেন্টে আপত্তি করুন',
    disputeReason: 'আপত্তির কারণ',
    disputeProof: 'প্রমাণ (URL বা বিবরণ)',
    profileCompleted: 'প্রোফাইল সম্পন্ন',
    profileIncomplete: 'প্রোফাইল সম্পন্ন করুন',
    completeProfileBanner: 'আপনার প্রোফাইল অসম্পূর্ণ। অন্যদের সাথে বিশ্বাস তৈরি করতে এটি সম্পন্ন করুন।',
  },
  banglish: {
    appName: 'Dena-Paona',
    tagline: 'Finance Ledger',
    dashboard: 'Dashboard',
    transactions: 'Lenden',
    addTransaction: 'Lenden Jog Korun',
    contacts: 'Porichiti / Khoje Nin',
    activityLog: 'Karjokolap Log',
    profile: 'Profile',
    adminPanel: 'Admin Panel',
    manageUsers: 'User Porichalona',
    logout: 'Log Out',
    mainMenu: 'Mul Menu',
    administration: 'Proshashan',
    welcomeBack: 'Abar Swagotom',
    signIn: 'Sign In',
    signInSubtitle: 'Apnar Dena-Paona account-e sign in korun',
    emailOrUsername: 'Email ba Username',
    password: 'Password',
    forgotPassword: 'Password bhule gechhen?',
    dontHaveAccount: 'Account nei?',
    createAccount: 'Account toiri korun',
    totalPaona: 'Moto Paona (Prapto)',
    totalDena: 'Moto Dena (Porishodhjogyo)',
    netBalance: 'Net Balance',
    contactLedger: 'Porichiti Ledger',
    recentActivity: 'Shaprontik Karjokola',
    quickActions: 'Druto Poddokshepo',
    recordPaona: '📥 Paona Record Korun',
    recordDena: '📤 Dena Record Korun',
    searchUsers: '🔍 User Khujun',
    noTransactions: 'Ekhono kono lenden nei',
    addFirst: 'Prothom lenden jog korun',
    paona: 'Paona',
    dena: 'Dena',
    amount: 'Poriman',
    paid: 'Porishodhito',
    remaining: 'Baki',
    status: 'Obostha',
    date: 'Tarikh',
    actions: 'Action',
    pending: 'Pending',
    partial: 'Aongshik',
    cleared: 'Cleared',
    contact: 'Porichiti',
    type: 'Dharon',
    notes: 'Note',
    search: 'Khojun',
    cancel: 'Batil',
    save: 'Save Korun',
    delete: 'Mochu Korun',
    edit: 'Edit Korun',
    viewAll: 'Sob Dekhun →',
    loading: 'Load hochhe...',
    moneyOweYou: 'Onera apnar kache rini',
    moneyYouOwe: 'Apni onader kache rini',
    fullName: 'Puro Nam',
    username: 'Username',
    email: 'Email',
    phone: 'Phone',
    age: 'Boyos',
    gender: 'Lingo',
    accountInfo: 'Account Tothyo',
    security: 'Nirapotta',
    memberSince: 'Sodo-pod theke',
    totalUsers: 'Moto User',
    verifiedUsers: 'Jachaikriti User',
    bannedUsers: 'Nishiddho User',
    totalTransactions: 'Lenden',
    totalVolume: 'Moto Poriman',
    ban: 'Ban Korun',
    unban: 'Ban Tullun',
    makeAdmin: '↑ Admin',
    removeAdmin: '↓ Sorao',
    joined: 'Jog diyechen',
    recordPayment: 'Payment Record Korun',
    paymentAmount: 'Payment-er Poriman',
    paymentHistory: 'Payment Itihash',
    outstandingBalance: 'Bokeyya Balance',
    fullyCleared: 'Sampurno Cleared!',
    addNew: '➕ Notun Jog Korun',
    back: '← Phire Jan',
    searchPlaceholder: 'Porichiti khujun...',
    noActivity: 'Ekhono kono karjokola nei',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Bhasha',
    settings: 'Settings',
    verifyEmail: 'Apnar Email Jachai Korun',
    verificationCode: 'Jachaikorono Code',
    verifyBtn: '✅ Email Jachai Korun',
    resendCode: '📨 Code Punray Pathon',
    backToLogin: '← Login-e Phirun',
    createYourAccount: 'Apnar Account Toiri Korun',
    joinSubtitle: 'Dena-Paona-te jog din ebong track shuru korun',
    male: 'Purush',
    female: 'Mohila',
    other: 'Onyanyo',
    selectGender: 'Lingo nirbachan korun',
    passwordStrengthWeak: 'Durbol',
    passwordStrengthMedium: 'Majhari',
    passwordStrengthStrong: 'Shoktishali',
    passwordStrength: 'Password-er Shokti',
    confirmPassword: 'Password Nishchit Korun',
    alreadyHaveAccount: 'Etomodhye account ache?',
    setUsername: 'Username Set Korun',
    usernameHint: 'Ekta ononnyo username bacha nin (3-30 char)',
    usernameAvailable: 'Username available!',
    usernameTaken: 'Username etomodhye newa hoyeche',
    completeProfile: 'Profile Sampurno Korun',
    completeProfileSubtitle: 'Aro tottho jog korun jate onera apnake khuje pete pare',
    skipForNow: 'Ekhoner jonno skip korun',
    bkashAvailable: 'Ami bKash / mobile banking payment grohon kori',
    profilePicture: 'Profile Chhobi',
    uploadPhoto: 'Chhobi Upload Korun',
    changePhoto: 'Chhobi Poriborton Korun',
    forgotPasswordTitle: 'Password Bhule Gechhen?',
    forgotPasswordSubtitle: 'Apnar email din, amra ekta reset code pathabo',
    sendResetCode: 'Reset Code Pathon',
    resetPassword: 'Password Reset Korun',
    resetCode: 'Reset Code',
    newPassword: 'Notun Password',
    pendingApproval: 'Onumoder Baki',
    approved: 'Onumodit',
    disputed: 'Bivrakit',
    forceApproved: 'Admin Onumodit',
    approvePayment: 'Payment Onumoder Korun',
    disputePayment: 'Payment-e Apotti Korun',
    disputeReason: 'Apottir Karon',
    disputeProof: 'Proman (URL ba biboran)',
    profileCompleted: 'Profile Sampurno',
    profileIncomplete: 'Profile Sampurno Korun',
    completeProfileBanner: 'Apnar profile osampurno. Onader shathe biswaas toiri korte eta sampurno korun.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('dp_lang') as Language;
    if (saved && ['en', 'bn', 'banglish'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('dp_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
